version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-dev_health}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    depends_on:
      - db
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    environment:
      - API_BASE_URL=/api
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:


