// Предустановленные достижения
export const defaultAchievements = [
  // === POMODORO ACHIEVEMENTS ===
  {
    name: "First Steps",
    description: "Complete your first pomodoro session",
    type: "pomodoro" as const,
    icon: "🍅",
    points: 10,
    requirements: { pomodoroSessions: 1 },
    rarity: "common" as const,
  },
  {
    name: "Beginner Pro",
    description: "Complete 5 pomodoro sessions",
    type: "pomodoro" as const,
    icon: "📚",
    points: 25,
    requirements: { pomodoroSessions: 5 },
    rarity: "common" as const,
  },
  {
    name: "Productive Day",
    description: "Complete 8 pomodoro sessions in a day",
    type: "pomodoro" as const,
    icon: "☀️",
    points: 50,
    requirements: { pomodoroSessions: 8 },
    rarity: "common" as const,
  },
  {
    name: "Week of Focus",
    description: "Complete 40 pomodoro sessions in a week",
    type: "pomodoro" as const,
    icon: "📅",
    points: 100,
    requirements: { pomodoroSessions: 40 },
    rarity: "rare" as const,
  },
  {
    name: "Time Master",
    description: "Complete 100 pomodoro sessions",
    type: "pomodoro" as const,
    icon: "⏰",
    points: 200,
    requirements: { pomodoroSessions: 100 },
    rarity: "rare" as const,
  },
  {
    name: "Professional",
    description: "Complete 500 pomodoro sessions",
    type: "pomodoro" as const,
    icon: "💼",
    points: 500,
    requirements: { pomodoroSessions: 500 },
    rarity: "epic" as const,
  },
  {
    name: "Productivity Legend",
    description: "Complete 1000 pomodoro sessions",
    type: "pomodoro" as const,
    icon: "👑",
    points: 1000,
    requirements: { pomodoroSessions: 1000 },
    rarity: "legendary" as const,
  },
  {
    name: "Infinite Productivity",
    description: "Complete 2000 pomodoro sessions",
    type: "pomodoro" as const,
    icon: "♾️",
    points: 2000,
    requirements: { pomodoroSessions: 2000 },
    rarity: "legendary" as const,
  },

  // === POSTURE ACHIEVEMENTS ===
  {
    name: "Stand Tall!",
    description: "Maintain good posture for 1 hour",
    type: "posture" as const,
    icon: "🧍",
    points: 20,
    requirements: { goodPostureTime: 3600000 },
    rarity: "common" as const,
  },
  {
    name: "Straight Back",
    description: "Maintain good posture for 5 hours",
    type: "posture" as const,
    icon: "📏",
    points: 50,
    requirements: { goodPostureTime: 18000000 },
    rarity: "common" as const,
  },
  {
    name: "Perfect Posture Day",
    description: "Maintain good posture for 8 hours",
    type: "posture" as const,
    icon: "🌅",
    points: 100,
    requirements: { goodPostureTime: 28800000 },
    rarity: "common" as const,
  },
  {
    name: "Week of Health",
    description: "Maintain good posture for 40 hours",
    type: "posture" as const,
    icon: "📆",
    points: 200,
    requirements: { goodPostureTime: 144000000 },
    rarity: "rare" as const,
  },
  {
    name: "Iron Spine",
    description: "Maintain good posture for 100 hours",
    type: "posture" as const,
    icon: "🦾",
    points: 500,
    requirements: { goodPostureTime: 360000000 },
    rarity: "epic" as const,
  },
  {
    name: "Posture Titan",
    description: "Maintain good posture for 500 hours",
    type: "posture" as const,
    icon: "🏛️",
    points: 1000,
    requirements: { goodPostureTime: 1800000000 },
    rarity: "epic" as const,
  },
  {
    name: "Immortal Spine",
    description: "Maintain good posture for 1000 hours",
    type: "posture" as const,
    icon: "💎",
    points: 2000,
    requirements: { goodPostureTime: 3600000000 },
    rarity: "legendary" as const,
  },

  // === BLINK ACHIEVEMENTS ===
  {
    name: "Don't Forget to Blink",
    description: "Receive 10 blink reminders",
    type: "blink" as const,
    icon: "👁️",
    points: 15,
    requirements: { blinkReminders: 10 },
    rarity: "common" as const,
  },
  {
    name: "Eye Care Advocate",
    description: "Receive 50 blink reminders",
    type: "blink" as const,
    icon: "👀",
    points: 40,
    requirements: { blinkReminders: 50 },
    rarity: "common" as const,
  },
  {
    name: "Eye Care Day",
    description: "Receive 100 blink reminders in a day",
    type: "blink" as const,
    icon: "🌞",
    points: 80,
    requirements: { blinkReminders: 100 },
    rarity: "common" as const,
  },
  {
    name: "Week of Healthy Vision",
    description: "Receive 500 blink reminders in a week",
    type: "blink" as const,
    icon: "📊",
    points: 150,
    requirements: { blinkReminders: 500 },
    rarity: "rare" as const,
  },
  {
    name: "Master of 20-20-20",
    description: "Receive 1000 blink reminders",
    type: "blink" as const,
    icon: "🎯",
    points: 300,
    requirements: { blinkReminders: 1000 },
    rarity: "rare" as const,
  },
  {
    name: "Vision Defender",
    description: "Receive 5000 blink reminders",
    type: "blink" as const,
    icon: "🛡️",
    points: 800,
    requirements: { blinkReminders: 5000 },
    rarity: "epic" as const,
  },
  {
    name: "Vision Legend",
    description: "Receive 10000 blink reminders",
    type: "blink" as const,
    icon: "👁️‍🗨️",
    points: 1500,
    requirements: { blinkReminders: 10000 },
    rarity: "legendary" as const,
  },

  // === TIME ACHIEVEMENTS ===
  {
    name: "First Minutes",
    description: "Spend 1 hour in work mode",
    type: "time" as const,
    icon: "⏱️",
    points: 10,
    requirements: { totalWorkTime: 3600000 },
    rarity: "common" as const,
  },
  {
    name: "Workday Warrior",
    description: "Spend 8 hours in work mode",
    type: "time" as const,
    icon: "💼",
    points: 50,
    requirements: { totalWorkTime: 28800000 },
    rarity: "common" as const,
  },
  {
    name: "Week of Labor",
    description: "Spend 40 hours in work mode",
    type: "time" as const,
    icon: "📈",
    points: 120,
    requirements: { totalWorkTime: 144000000 },
    rarity: "rare" as const,
  },
  {
    name: "Month of Productivity",
    description: "Spend 160 hours in work mode",
    type: "time" as const,
    icon: "📅",
    points: 300,
    requirements: { totalWorkTime: 576000000 },
    rarity: "rare" as const,
  },
  {
    name: "Workaholic",
    description: "Spend 1000 hours in work mode",
    type: "time" as const,
    icon: "🔥",
    points: 800,
    requirements: { totalWorkTime: 3600000000 },
    rarity: "epic" as const,
  },
  {
    name: "Time Master",
    description: "Spend 2000 hours in work mode",
    type: "time" as const,
    icon: "⏰",
    points: 1500,
    requirements: { totalWorkTime: 7200000000 },
    rarity: "epic" as const,
  },
  {
    name: "Lord of Time",
    description: "Spend 5000 hours in work mode",
    type: "time" as const,
    icon: "⌛",
    points: 3000,
    requirements: { totalWorkTime: 18000000000 },
    rarity: "legendary" as const,
  },

  // === STREAK ACHIEVEMENTS ===
  {
    name: "First Days",
    description: "3 consecutive days with good posture",
    type: "streak" as const,
    icon: "🌱",
    points: 30,
    requirements: { consecutiveGoodPostureDays: 3 },
    rarity: "common" as const,
  },
  {
    name: "Health Week",
    description: "7 consecutive days with good posture",
    type: "streak" as const,
    icon: "📅",
    points: 100,
    requirements: { consecutiveGoodPostureDays: 7 },
    rarity: "rare" as const,
  },
  {
    name: "Two Weeks of Strength",
    description: "14 consecutive days with good posture",
    type: "streak" as const,
    icon: "💪",
    points: 200,
    requirements: { consecutiveGoodPostureDays: 14 },
    rarity: "rare" as const,
  },
  {
    name: "Month of Discipline",
    description: "30 consecutive days with good posture",
    type: "streak" as const,
    icon: "🗓️",
    points: 500,
    requirements: { consecutiveGoodPostureDays: 30 },
    rarity: "epic" as const,
  },
  {
    name: "Quarter of a Champion",
    description: "90 consecutive days with good posture",
    type: "streak" as const,
    icon: "🏆",
    points: 1000,
    requirements: { consecutiveGoodPostureDays: 90 },
    rarity: "epic" as const,
  },
  {
    name: "Half-Year Legend",
    description: "180 consecutive days with good posture",
    type: "streak" as const,
    icon: "👑",
    points: 2000,
    requirements: { consecutiveGoodPostureDays: 180 },
    rarity: "legendary" as const,
  },
  {
    name: "Year of Immortality",
    description: "365 consecutive days with good posture",
    type: "streak" as const,
    icon: "🌟",
    points: 5000,
    requirements: { consecutiveGoodPostureDays: 365 },
    rarity: "legendary" as const,
  },

  // === COMBINED ACHIEVEMENTS ===
  {
    name: "Work-Life Balance",
    description: "50 pomodoro sessions + 50 hours of good posture",
    type: "pomodoro" as const,
    icon: "⚖️",
    points: 150,
    requirements: { pomodoroSessions: 50, goodPostureTime: 180000000 },
    rarity: "rare" as const,
  },
  {
    name: "Triad of Health",
    description: "100 pomodoro + 100 hours posture + 1000 blink reminders",
    type: "pomodoro" as const,
    icon: "🔺",
    points: 500,
    requirements: {
      pomodoroSessions: 100,
      goodPostureTime: 360000000,
      blinkReminders: 1000,
    },
    rarity: "epic" as const,
  },
  {
    name: "Master of All Arts",
    description: "500 pomodoro + 500h posture + 5000 blinks + 1000h work",
    type: "pomodoro" as const,
    icon: "🎭",
    points: 1500,
    requirements: {
      pomodoroSessions: 500,
      goodPostureTime: 1800000000,
      blinkReminders: 5000,
      totalWorkTime: 3600000000,
    },
    rarity: "legendary" as const,
  },

  // === SPECIAL ACHIEVEMENTS ===
  {
    name: "Early Bird",
    description: "Start work before 8 AM for 7 consecutive days",
    type: "streak" as const,
    icon: "🌅",
    points: 200,
    requirements: { consecutiveGoodPostureDays: 7 },
    rarity: "rare" as const,
  },
  {
    name: "Night Owl",
    description: "Work after 10 PM for 30 consecutive days",
    type: "streak" as const,
    icon: "🦉",
    points: 300,
    requirements: { consecutiveGoodPostureDays: 30 },
    rarity: "epic" as const,
  },
  {
    name: "Weekend Warrior",
    description: "Work on weekends for 10 consecutive weeks",
    type: "streak" as const,
    icon: "⚔️",
    points: 400,
    requirements: { consecutiveGoodPostureDays: 70 },
    rarity: "epic" as const,
  },
  {
    name: "Marathoner",
    description: "Spend 12 consecutive hours in work mode",
    type: "time" as const,
    icon: "🏃",
    points: 250,
    requirements: { totalWorkTime: 43200000 },
    rarity: "rare" as const,
  },
  {
    name: "Ultramarathoner",
    description: "Spend 24 consecutive hours in work mode",
    type: "time" as const,
    icon: "🏃‍♂️",
    points: 1000,
    requirements: { totalWorkTime: 86400000 },
    rarity: "legendary" as const,
  },

  // === SEASONAL ACHIEVEMENTS ===
  {
    name: "Spring Renewal",
    description: "Reach 1000 health points in spring",
    type: "posture" as const,
    icon: "🌸",
    points: 300,
    requirements: { goodPostureTime: 180000000 },
    rarity: "rare" as const,
  },
  {
    name: "Summer Heat",
    description: "Work in hot weather for 30 consecutive days",
    type: "streak" as const,
    icon: "☀️",
    points: 400,
    requirements: { consecutiveGoodPostureDays: 30 },
    rarity: "epic" as const,
  },
  {
    name: "Autumn Melancholy",
    description: "Spend 100 hours working in rainy weather",
    type: "time" as const,
    icon: "🍂",
    points: 350,
    requirements: { totalWorkTime: 360000000 },
    rarity: "rare" as const,
  },
  {
    name: "Winter Frost",
    description: "Work at temperatures below 0°C for 50 days",
    type: "streak" as const,
    icon: "❄️",
    points: 600,
    requirements: { consecutiveGoodPostureDays: 50 },
    rarity: "epic" as const,
  },

  // === PROFESSIONAL ACHIEVEMENTS ===
  {
    name: "Intern",
    description: "First month using the app",
    type: "time" as const,
    icon: "🎓",
    points: 100,
    requirements: { totalWorkTime: 144000000 },
    rarity: "common" as const,
  },
  {
    name: "Junior Developer",
    description: "3 months using the app",
    type: "time" as const,
    icon: "👨‍💻",
    points: 300,
    requirements: { totalWorkTime: 432000000 },
    rarity: "rare" as const,
  },
  {
    name: "Developer",
    description: "6 months using the app",
    type: "time" as const,
    icon: "👨‍💼",
    points: 600,
    requirements: { totalWorkTime: 864000000 },
    rarity: "rare" as const,
  },
  {
    name: "Senior Developer",
    description: "1 year using the app",
    type: "time" as const,
    icon: "👨‍🔬",
    points: 1200,
    requirements: { totalWorkTime: 1728000000 },
    rarity: "epic" as const,
  },
  {
    name: "Tech Lead",
    description: "2 years using the app",
    type: "time" as const,
    icon: "👨‍💼",
    points: 2500,
    requirements: { totalWorkTime: 3456000000 },
    rarity: "epic" as const,
  },
  {
    name: "Architect",
    description: "5 years using the app",
    type: "time" as const,
    icon: "🏗️",
    points: 5000,
    requirements: { totalWorkTime: 8640000000 },
    rarity: "legendary" as const,
  },

  // === GAMING ACHIEVEMENTS ===
  {
    name: "Newbie",
    description: "Reach level 1",
    type: "posture" as const,
    icon: "🥉",
    points: 50,
    requirements: { goodPostureTime: 18000000 },
    rarity: "common" as const,
  },
  {
    name: "Enthusiast",
    description: "Reach level 5",
    type: "posture" as const,
    icon: "🥈",
    points: 150,
    requirements: { goodPostureTime: 90000000 },
    rarity: "common" as const,
  },
  {
    name: "Professional",
    description: "Reach level 10",
    type: "posture" as const,
    icon: "🥇",
    points: 300,
    requirements: { goodPostureTime: 180000000 },
    rarity: "rare" as const,
  },
  {
    name: "Expert",
    description: "Reach level 25",
    type: "posture" as const,
    icon: "💎",
    points: 800,
    requirements: { goodPostureTime: 450000000 },
    rarity: "epic" as const,
  },
  {
    name: "Master",
    description: "Reach level 50",
    type: "posture" as const,
    icon: "👑",
    points: 1500,
    requirements: { goodPostureTime: 900000000 },
    rarity: "epic" as const,
  },
  {
    name: "Legend",
    description: "Reach level 100",
    type: "posture" as const,
    icon: "🌟",
    points: 3000,
    requirements: { goodPostureTime: 1800000000 },
    rarity: "legendary" as const,
  },

  // === MILESTONES ===
  {
    name: "First Hundred",
    description: "Reach 100 health points",
    type: "posture" as const,
    icon: "💯",
    points: 50,
    requirements: { goodPostureTime: 30000000 },
    rarity: "common" as const,
  },
  {
    name: "First Thousand",
    description: "Reach 1000 health points",
    type: "posture" as const,
    icon: "1️⃣0️⃣0️⃣0️⃣",
    points: 200,
    requirements: { goodPostureTime: 300000000 },
    rarity: "rare" as const,
  },
  {
    name: "First Ten Thousand",
    description: "Reach 10000 health points",
    type: "posture" as const,
    icon: "🔟0️⃣0️⃣0️⃣0️⃣",
    points: 500,
    requirements: { goodPostureTime: 3000000000 },
    rarity: "epic" as const,
  },
  {
    name: "Hundred Thousand",
    description: "Reach 100000 health points",
    type: "posture" as const,
    icon: "💎",
    points: 1000,
    requirements: { goodPostureTime: 30000000000 },
    rarity: "legendary" as const,
  },

  // === SPECIAL SERIES ===
  {
    name: "Bronze Warrior",
    description: "100h work + 100 pomodoro + 1000 blink reminders",
    type: "pomodoro" as const,
    icon: "🥉",
    points: 300,
    requirements: {
      totalWorkTime: 360000000,
      pomodoroSessions: 100,
      blinkReminders: 1000,
    },
    rarity: "rare" as const,
  },
  {
    name: "Silver Knight",
    description: "500h work + 500 pomodoro + 5000 blink reminders",
    type: "pomodoro" as const,
    icon: "🥈",
    points: 800,
    requirements: {
      totalWorkTime: 1800000000,
      pomodoroSessions: 500,
      blinkReminders: 5000,
    },
    rarity: "epic" as const,
  },
  {
    name: "Golden King",
    description: "1000h work + 1000 pomodoro + 10000 blink reminders",
    type: "pomodoro" as const,
    icon: "🥇",
    points: 1500,
    requirements: {
      totalWorkTime: 3600000000,
      pomodoroSessions: 1000,
      blinkReminders: 10000,
    },
    rarity: "epic" as const,
  },
  {
    name: "Platinum Emperor",
    description: "2000h work + 2000 pomodoro + 20000 blink reminders",
    type: "pomodoro" as const,
    icon: "💎",
    points: 3000,
    requirements: {
      totalWorkTime: 7200000000,
      pomodoroSessions: 2000,
      blinkReminders: 20000,
    },
    rarity: "legendary" as const,
  },

  // === COSMIC ACHIEVEMENTS ===
  {
    name: "Lunatic",
    description: "Work at night for 100 consecutive days",
    type: "streak" as const,
    icon: "🌙",
    points: 800,
    requirements: { consecutiveGoodPostureDays: 100 },
    rarity: "epic" as const,
  },
  {
    name: "Martian",
    description: "Work at unusual hours for 365 days",
    type: "streak" as const,
    icon: "🚀",
    points: 1500,
    requirements: { consecutiveGoodPostureDays: 365 },
    rarity: "legendary" as const,
  },
  {
    name: "Alien",
    description: "Achieve the impossible: all achievements at once",
    type: "pomodoro" as const,
    icon: "👽",
    points: 10000,
    requirements: {
      pomodoroSessions: 5000,
      goodPostureTime: 7200000000,
      blinkReminders: 50000,
      totalWorkTime: 18000000000,
      consecutiveGoodPostureDays: 1000,
    },
    rarity: "legendary" as const,
  },

  // === HUMOROUS ACHIEVEMENTS ===
  {
    name: "Coffee Addict",
    description: "Work with coffee breaks for 50 days",
    type: "streak" as const,
    icon: "☕",
    points: 200,
    requirements: { consecutiveGoodPostureDays: 50 },
    rarity: "common" as const,
  },
  {
    name: "Pizza Master",
    description: "Work while eating for 100 days",
    type: "streak" as const,
    icon: "🍕",
    points: 300,
    requirements: { consecutiveGoodPostureDays: 100 },
    rarity: "rare" as const,
  },
  {
    name: "Cat Companion",
    description: "Work with pets for 200 days",
    type: "streak" as const,
    icon: "🐱",
    points: 400,
    requirements: { consecutiveGoodPostureDays: 200 },
    rarity: "epic" as const,
  },
  {
    name: "Home Office",
    description: "Work in pajamas for 365 days",
    type: "streak" as const,
    icon: "🏠",
    points: 600,
    requirements: { consecutiveGoodPostureDays: 365 },
    rarity: "epic" as const,
  },

  // === TECH ACHIEVEMENTS ===
  {
    name: "Beta Tester",
    description: "Use the app for one month",
    type: "time" as const,
    icon: "🧪",
    points: 100,
    requirements: { totalWorkTime: 144000000 },
    rarity: "common" as const,
  },
  {
    name: "Early Adopter",
    description: "Use the app for 3 months",
    type: "time" as const,
    icon: "🚀",
    points: 250,
    requirements: { totalWorkTime: 432000000 },
    rarity: "rare" as const,
  },
  {
    name: "Loyal User",
    description: "Use the app for 1 year",
    type: "time" as const,
    icon: "💎",
    points: 500,
    requirements: { totalWorkTime: 1728000000 },
    rarity: "epic" as const,
  },
  {
    name: "Pioneer",
    description: "Use the app for 5 years",
    type: "time" as const,
    icon: "🏆",
    points: 1000,
    requirements: { totalWorkTime: 8640000000 },
    rarity: "legendary" as const,
  },

  // === SOCIAL ACHIEVEMENTS ===
  {
    name: "Team Player",
    description: "Work in a team for 30 consecutive days",
    type: "streak" as const,
    icon: "👥",
    points: 200,
    requirements: { consecutiveGoodPostureDays: 30 },
    rarity: "common" as const,
  },
  {
    name: "Team Leader",
    description: "Be the top performer in team for 100 days",
    type: "streak" as const,
    icon: "👑",
    points: 500,
    requirements: { consecutiveGoodPostureDays: 100 },
    rarity: "rare" as const,
  },
  {
    name: "Mentor",
    description: "Help others for 365 consecutive days",
    type: "streak" as const,
    icon: "🎓",
    points: 800,
    requirements: { consecutiveGoodPostureDays: 365 },
    rarity: "epic" as const,
  },

  // === MEDITATIVE ACHIEVEMENTS ===
  {
    name: "Zen Master",
    description: "Work in complete silence for 50 days",
    type: "streak" as const,
    icon: "🧘",
    points: 300,
    requirements: { consecutiveGoodPostureDays: 50 },
    rarity: "rare" as const,
  },
  {
    name: "Meditator",
    description: "Take meditation breaks for 100 days",
    type: "streak" as const,
    icon: "🕉️",
    points: 400,
    requirements: { consecutiveGoodPostureDays: 100 },
    rarity: "epic" as const,
  },
  {
    name: "Enlightened",
    description: "Balance work and rest for 365 days",
    type: "streak" as const,
    icon: "✨",
    points: 1000,
    requirements: { consecutiveGoodPostureDays: 365 },
    rarity: "legendary" as const,
  },

  // === FINAL ACHIEVEMENTS ===
  {
    name: "Immortal",
    description: "Achieve all possible achievements",
    type: "pomodoro" as const,
    icon: "💀",
    points: 50000,
    requirements: {
      pomodoroSessions: 10000,
      goodPostureTime: 36000000000,
      blinkReminders: 100000,
      totalWorkTime: 72000000000,
      consecutiveGoodPostureDays: 1000,
    },
    rarity: "legendary" as const,
  },
  {
    name: "Productivity God",
    description: "Become a legend of productivity",
    type: "pomodoro" as const,
    icon: "⚡",
    points: 100000,
    requirements: {
      pomodoroSessions: 50000,
      goodPostureTime: 180000000000,
      blinkReminders: 500000,
      totalWorkTime: 360000000000,
      consecutiveGoodPostureDays: 3650,
    },
    rarity: "legendary" as const,
  },
];
